# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Tech
paginate:       5
baseurl:        ""
url:            "https://tech-the8days.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Walter
  url:          http://8days.com
  email:        tech@the8days.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
plugins:
  - jekyll-paginate
